lang: en_US

computer:
  block: NETHER_BRICK_STAIRS
  admin-computer:
    enabled: false
    block: POLISHED_BLACKSTONE_STAIRS
  craft:
    enabled: true
    shape:
      - "ITI"
      - "PGP"
      - "RCR"
    items:
      I: REDSTONE
      P: HEAVY_WEIGHTED_PRESSURE_PLATE
      G: GLASS_PANE
      C: COMPARATOR
      R: REPEATER
      T: REDSTONE_TORCH
viewers:
  can_chat: true
  get_items_without_permission: true
  timed-actions:
    connect: 3
    disconnect: 3
    spot: 5
  bossbar: true
  blocked-commands:
    - "/tp"
    - "/tpa"
    - "/tphere"
    - "/tpahere"
    - "/home"
    - "/warp"
    - "/suicide"
camera:
  experimental_view: false
  zoom_item: true
  craft:
    enabled: true
    shape:
      - "RPP"
      - "PDG"
      - "LCP"
    items:
      R: REDSTONE_BLOCK
      P: HEAVY_WEIGHTED_PRESSURE_PLATE
      D: DISPENSER
      G: GLASS_PANE
      L: DAYLIGHT_DETECTOR
      C: COMPARATOR
  skins:
    "Green Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTM1MTcwNWM3NjVjNGYzNjRjZDk0ZTJjYTk1MjA0ZjdlZWM4YzNjNDdmNDI1ZDZkOTA1MDkwNDVmOTcxNDc2OSJ9fX0="
    "Blue Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzZlNTAyYmM2NzA3ODQ5Zjg1ZTdjMTNmZDYyZTk2ZDZhYmI0ZWM0MTJiMjIxMjNhODdhM2ZiZDQ0ZjcxNDQwZiJ9fX0="
    "Light-Blue Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjBhMGFjNjgwNjcwNGQ5OWJmZWMxNTBhZGZjNzlkMmY1NTI4NmY1ODgzNjA0MzkzM2Q4MWVkOWY4MGMwYmExOSJ9fX0="
    "Diamond Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzA2MTA3ZGVlN2Y4ZDI5OGE0NDg2ZmQ0ZDYwNDRiOTA5MjJlNjNiZDI5ZjA2OWZkZmJmMjZmNTRmZDRlYmVjNSJ9fX0="
    "White Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjVkODdhNGMzYmJjNDU1NjY1YTU1OTI5NzA4NGUwNTliMjk4NmU1YzIyNThiNDQ5ZWEwZjE3YTBiMTJhZGRhYyJ9fX0="
    "White Camera 2": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDUwYjE3NjgyMWQ5YjBkM2E5ZmQyYmY5MmU3OTc5Y2M0NGY0ZmRhNjY2YjgyYTQ2NDdkZGIwY2ZjMDc1MDFkNiJ9fX0="
    "Copper Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDE1ZTQ3MDgwNWQ1ZmM2MTFjNDRiODdjMzllN2U0ZGZkNDc0MDQ5YjI0ZjNmNmJiYTIzMGUyNTBmOWI0Yjg3YyJ9fX0="
    "Old Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjRjOGZmYmJhZjUyZjU5MTcxZjk0NDVmNjg0ODVjZjdlN2UxZDZhOTA4N2VlN2VmOWIzODY5YTcyMTE3NzlmIn19fQ=="
    "Old Camera 2": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWRmODkwOTQ5OGMyNWY2ZTc1ZWYxOWUzNzZhN2Y4NGY2MWFmMjM0NTI1ZDYzOWJhNDYzZjk5MWY0YzgyZDAifX19"
    "Camera 2": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzRhNzQ0NTdjOTM1OTQ5ZGYxZmU3ZWUzOTViNDhjNDQ4YjMzZTYwMzM0MTMwOTU4NTM2YjE0OGViZDZjNiJ9fX0="
    "Camera 3": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTQ0MjJhODJjODk5YTljMTQ1NDM4NGQzMmNjNTRjNGFlN2ExYzRkNzI0MzBlNmU0NDZkNTNiOGIzODVlMzMwIn19fQ=="
    "Recording Camera": "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzdmNzM3YjE2ZjliOGE0Yjg2YjkzOTQyNDRmNGE3OWEyM2ExNzk5NDliY2QzMGQzYTVlOTI1YWFjMzE3ZDgzMSJ9fX0="
